#app_id: 1fc3615a-b851-4d1e-83ff-5428dd7423ec
#app_secret: akhOGU276^=|kifvPVHP62(
app_id: 72dac7a9-0825-4870-88de-63a9d60b6a19
app_secret: RrrV::h0mUF:DRnAWMXq@xa9NYXAqS12
redirect: http://localhost:8000/tutorial/callback
scopes: openid profile offline_access user.read calendars.read User.Read.All User.ReadWrite.All Directory.Read.All Directory.ReadWrite.All
authority: https://login.microsoftonline.com/common
authorize_endpoint: /oauth2/v2.0/authorize
token_endpoint: /oauth2/v2.0/token